name: codesign-test

on:
  workflow_dispatch:
  push:
    branches:
      - "icloud-keychain"

jobs:
# ================================
#              macOS
# ================================
  osx-build:
    name: Build macOS
    runs-on: macos-latest
    strategy:
      matrix:
        runtime: [ osx-x64, osx-arm64 ]
    steps:
    - uses: actions/checkout@v3

    - name: Set up dotnet
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.201

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build src/osx/Installer.Mac/*.csproj \
         --configuration=MacRelease --no-self-contained \
         --runtime=${{ matrix.runtime }}

    - name: Run macOS unit tests
      run: |
        dotnet test --configuration=MacRelease

    - name: Lay out payload and symbols
      run: |
        src/osx/Installer.Mac/layout.sh \
         --configuration=MacRelease --output=payload \
         --symbol-output=symbols --runtime=${{ matrix.runtime }}

    - name: Create keychain
      env:
        CERT_BASE64: ${{ secrets.DEVELOPER_CERTIFICATE_BASE64 }}
        CERT_PASSPHRASE: ${{ secrets.DEVELOPER_CERTIFICATE_PASSWORD }}
      run: |
        security create-keychain -p pwd $RUNNER_TEMP/buildagent.keychain
        security default-keychain -s $RUNNER_TEMP/buildagent.keychain
        security unlock-keychain -p pwd $RUNNER_TEMP/buildagent.keychain
        echo $CERT_BASE64 | base64 -D > $RUNNER_TEMP/cert.p12
        security import $RUNNER_TEMP/cert.p12 -k $RUNNER_TEMP/buildagent.keychain -P $CERT_PASSPHRASE -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k pwd $RUNNER_TEMP/buildagent.keychain

    - name: Developer sign
      env:
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        .github/run_developer_signing.sh payload $APPLE_TEAM_ID $GITHUB_WORKSPACE/src/osx/Installer.Mac/entitlements.xml

    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tmp.${{ matrix.runtime }}-build
        path: |
          payload
          symbols

  osx-payload-sign:
    name: Sign macOS payload
    # ESRP service requires signing to run on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        runtime: [ osx-x64, osx-arm64 ]
    needs: osx-build
    steps:
    - uses: actions/checkout@v3

    - name: Download payload
      uses: actions/download-artifact@v3
      with:
        name: tmp.${{ matrix.runtime }}-build

    - name: Zip unsigned payload
      shell: pwsh
      run: |
        Compress-Archive -Path payload payload/payload.zip
        cd payload
        Get-ChildItem -Exclude payload.zip | Remove-Item -Recurse -Force

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up ESRP client
      shell: pwsh
      env:
        AZURE_VAULT: ${{ secrets.AZURE_VAULT }}
        AUTH_CERT: ${{ secrets.AZURE_VAULT_AUTH_CERT_NAME }}
        REQUEST_SIGNING_CERT: ${{ secrets.AZURE_VAULT_REQUEST_SIGNING_CERT_NAME }}
      run: |
        .github\set_up_esrp.ps1

    - name: Run ESRP client
      shell: pwsh
      env:
        AZURE_AAD_ID: ${{ secrets.AZURE_AAD_ID }}
        APPLE_KEY_CODE: ${{ secrets.APPLE_KEY_CODE }}
        APPLE_SIGNING_OP_CODE: ${{ secrets.APPLE_SIGNING_OPERATION_CODE }}
      run: |
        python .github\run_esrp_signing.py payload `
         $env:APPLE_KEY_CODE $env:APPLE_SIGNING_OP_CODE `
         --params 'Hardening' '--options=runtime'

    - name: Unzip signed payload
      shell: pwsh
      run: |
        Expand-Archive signed/payload.zip -DestinationPath signed
        Remove-Item signed/payload.zip

    - name: Upload signed payload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.runtime }}-payload-sign
        path: |
          signed

  osx-pack:
    name: Package macOS payload
    runs-on: macos-latest
    strategy:
      matrix:
        runtime: [ osx-x64, osx-arm64 ]
    needs: osx-payload-sign
    steps:
    - uses: actions/checkout@v3

    - name: Set version environment variable
      run: echo "VERSION=$(cat VERSION | sed -E 's/.[0-9]+$//')" >> $GITHUB_ENV

    - name: Set up dotnet
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.201

    - name: Download signed payload
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.runtime }}-payload-sign

    - name: Create component package
      run: |
        src/osx/Installer.Mac/pack.sh --payload=payload \
         --version=$VERSION \
         --output=components/com.microsoft.gitcredentialmanager.component.pkg

    - name: Create product archive
      run: |
        src/osx/Installer.Mac/dist.sh --package-path=components \
         --version=$VERSION --runtime=${{ matrix.runtime }} \
         --output=pkg/gcm-${{ matrix.runtime }}-$VERSION.pkg || exit 1

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: tmp.${{ matrix.runtime }}-pack
        path: |
          pkg

  osx-sign:
    name: Sign and notarize macOS package
    # ESRP service requires signing to run on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        runtime: [ osx-x64, osx-arm64 ]
    needs: osx-pack
    steps:
    - uses: actions/checkout@v3

    - name: Download unsigned package
      uses: actions/download-artifact@v3
      with:
        name: tmp.${{ matrix.runtime }}-pack
        path: pkg

    - name: Zip unsigned package
      shell: pwsh
      run: |
        Compress-Archive -Path pkg/*.pkg pkg/gcm-pkg.zip
        cd pkg
        Get-ChildItem -Exclude gcm-pkg.zip | Remove-Item -Recurse -Force

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up ESRP client
      shell: pwsh
      env:
        AZURE_VAULT: ${{ secrets.AZURE_VAULT }}
        AUTH_CERT: ${{ secrets.AZURE_VAULT_AUTH_CERT_NAME }}
        REQUEST_SIGNING_CERT: ${{ secrets.AZURE_VAULT_REQUEST_SIGNING_CERT_NAME }}
      run: |
        .github\set_up_esrp.ps1

    - name: Sign package
      shell: pwsh
      env:
        AZURE_AAD_ID: ${{ secrets.AZURE_AAD_ID }}
        APPLE_KEY_CODE: ${{ secrets.APPLE_KEY_CODE }}
        APPLE_SIGNING_OP_CODE: ${{ secrets.APPLE_SIGNING_OPERATION_CODE }}
      run: |
        python .github\run_esrp_signing.py pkg $env:APPLE_KEY_CODE $env:APPLE_SIGNING_OP_CODE

    - name: Unzip signed package
      shell: pwsh
      run: |
        mkdir unsigned
        Expand-Archive -LiteralPath signed\gcm-pkg.zip -DestinationPath .\unsigned -Force
        Remove-Item signed\gcm-pkg.zip -Force

    - name: Notarize signed package
      shell: pwsh
      env:
        AZURE_AAD_ID: ${{ secrets.AZURE_AAD_ID }}
        APPLE_KEY_CODE: ${{ secrets.APPLE_KEY_CODE }}
        APPLE_NOTARIZATION_OP_CODE: ${{ secrets.APPLE_NOTARIZATION_OPERATION_CODE }}
      run: |
        python .github\run_esrp_signing.py unsigned $env:APPLE_KEY_CODE $env:APPLE_NOTARIZATION_OP_CODE --params 'BundleId' 'com.microsoft.gitcredentialmanager'

    - name: Publish signed package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.runtime }}-sign
        path: signed/*.pkg
